version: "3.4"

services:
  flight-web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
