@Web_HostAddress = http://localhost:8080
@FlightNumber = DEF456
@departureCity = 
@destinationCity = 

###

# Get Flights
GET {{Web_HostAddress}}/api/flights
?flightNumber={{FlightNumber}}
&departureCity={{departureCity}}
&destinationCity={{destinationCity}}

###